command: code
dialog_code_input: codeinput # comment this line if you don't want dialog input code
gui-list-enabled: true

storage:
  type: yaml
  uri: ""
  host: localhost
  port: 3306
  database: claimo
  username: root
  password: ""
  table-prefix: claimo_
  pool-size: 10