name: Claimo
version: '${version}'

folia-supported: true
main: zone.vao.claimo.Claimo
api-version: '1.21'
load: POSTWORLD
author: "Naimad (dc: 4g0)"
softdepend: [PlaceholderAPI, Vault, MiniPlaceholders]

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
  - "com.zaxxer:HikariCP:${hikariVersion}"
  - "org.xerial:sqlite-jdbc:3.50.1.0"
  - "com.mysql:mysql-connector-j:9.3.0"
  - "org.postgresql:postgresql:42.7.7"
  - "org.mongodb:mongodb-driver-sync:${mongoVersion}"

permissions:
  claimo.use:
    description: Allows redeeming voucher codes.
    default: true
  claimo.admin:
    description: Allows reloading the Claimo configuration.
    default: op
